name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:10
      
    # strategy:
    #   matrix:
    #     node-version: [10.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}
      - run: node --version
      - run: yarn install --frozen-lockfile
      - run: yarn test
